[package]
name = "marengo-jetson"
version = "0.1.0"
description = "Marengo runtime on Jetson"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "marengo-jetson"
path = "src/main.rs"

[dependencies]
chappe = { path = "../../crates/chappe" }
fouche = { path = "../../crates/fouche" }
marengo-support.workspace = true
talleyrand = { path = "../../crates/talleyrand" }
tokio.workspace = true
tracing.workspace = true
