[package]
name = "davout"
version = "0.1.0"
description = "Safety supervision for Marengo"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
armee-kinematics.workspace = true
marengo-config.workspace = true
robstride.workspace = true
thiserror.workspace = true
tracing.workspace = true
urdf-rs.workspace = true
