[package]
name = "wave-demo"
version = "0.1.0"
description = "Demo trajectory / wave motion"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license = "MIT OR Apache-2.0"

[[bin]]
name = "wave-demo"
path = "src/main.rs"

[dependencies]
berthier = { path = "../../crates/berthier" }
