[package]
name = "berthier"
version = "0.1.0"
description = "Realtime control stack for Marengo (Berthier)"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
armee-dynamics.workspace = true
armee-kinematics.workspace = true
armee-proto.workspace = true
chappe.workspace = true
davout.workspace = true
marengo-config.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
proptest = { workspace = true }
davout = { workspace = true }
robstride = { workspace = true }
armee-dynamics = { workspace = true }

