#!/usr/bin/env bash
# Install Marengo runtime layout on Raspberry Pi (run on the Pi as root).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=deploy-lib.sh
source "${ROOT}/scripts/deploy-lib.sh"
INSTALL_ROOT="${MARENGO_INSTALL_ROOT:-/opt/marengo}"
RUN_USER="${MARENGO_USER:-marengo}"
DEPLOY_USER="${MARENGO_DEPLOY_USER:-${SUDO_USER:-joey}}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "run as root: sudo $0" >&2
  exit 1
fi

echo "Installing Marengo to ${INSTALL_ROOT} (user ${RUN_USER})"

# Bench default: stop always-on control so manual/MCP sessions own marengo-pi.
systemctl stop marengo-pi.service 2>/dev/null || true
pkill -f "${INSTALL_ROOT}/bin/marengo-pi" 2>/dev/null || true

if ! id "$RUN_USER" &>/dev/null; then
  useradd --system --home "$INSTALL_ROOT" --shell /usr/sbin/nologin "$RUN_USER"
fi
usermod -aG dialout "$RUN_USER" || true
usermod -aG i2c "$RUN_USER" || true
if id "$DEPLOY_USER" &>/dev/null; then
  usermod -aG "$RUN_USER" "$DEPLOY_USER" || true
  usermod -aG i2c "$DEPLOY_USER" || true
fi

mkdir -p \
  "${INSTALL_ROOT}/bin" \
  "${INSTALL_ROOT}/config" \
  "${INSTALL_ROOT}/assets" \
  "${INSTALL_ROOT}/www" \
  "${INSTALL_ROOT}/var/log" \
  "${INSTALL_ROOT}/var/log/blobs" \
  "${INSTALL_ROOT}/var/calibration" \
  "${INSTALL_ROOT}/var/gateway/tls"
chmod 775 "${INSTALL_ROOT}/var" "${INSTALL_ROOT}/var/log" "${INSTALL_ROOT}/var/calibration" 2>/dev/null || true
chown root:"${RUN_USER}" "${INSTALL_ROOT}/var" "${INSTALL_ROOT}/var/log" "${INSTALL_ROOT}/var/calibration" 2>/dev/null || true

PI_BIN="${ROOT}/target/release/marengo-pi"
GATEWAY_BIN="${ROOT}/target/release/marengo-gateway"
LOG_CLI_BIN="${ROOT}/target/release/marengo-log-cli"
REPL_BIN="${ROOT}/target/release/motor-repl"
IMU_PROBE_BIN="${ROOT}/target/release/imu-probe"
# Flat deploy layout (legacy rsync): binaries at repo root
if [[ ! -f "$PI_BIN" && -f "${ROOT}/marengo-pi" ]]; then
  PI_BIN="${ROOT}/marengo-pi"
fi
if [[ ! -f "$REPL_BIN" && -f "${ROOT}/motor-repl" ]]; then
  REPL_BIN="${ROOT}/motor-repl"
fi
if [[ ! -f "$PI_BIN" ]]; then
  echo "error: marengo-pi not found under ${ROOT}/target/release/ or ${ROOT}/" >&2
  exit 1
fi
install -m 755 "$PI_BIN" "${INSTALL_ROOT}/bin/marengo-pi"
if [[ -f "$GATEWAY_BIN" ]]; then
  install -m 755 "$GATEWAY_BIN" "${INSTALL_ROOT}/bin/marengo-gateway"
fi
if [[ -f "$LOG_CLI_BIN" ]]; then
  install -m 755 "$LOG_CLI_BIN" "${INSTALL_ROOT}/bin/marengo-log-cli"
fi
if [[ -f "$REPL_BIN" ]]; then
  install -m 755 "$REPL_BIN" "${INSTALL_ROOT}/bin/motor-repl"
fi
if [[ -f "$IMU_PROBE_BIN" ]]; then
  install -m 755 "$IMU_PROBE_BIN" "${INSTALL_ROOT}/bin/imu-probe"
fi

rsync -a --delete "${ROOT}/config/" "${INSTALL_ROOT}/config/"
rsync -a "${ROOT}/assets/" "${INSTALL_ROOT}/assets/"
rsync -a "${ROOT}/scripts/" "${INSTALL_ROOT}/scripts/"
WWW_SRC=""
if [[ -d "${ROOT}/consul/dist" ]] && [[ -f "${ROOT}/consul/dist/index.html" ]]; then
  WWW_SRC="${ROOT}/consul/dist"
elif [[ -d "${ROOT}/www" ]] && [[ -f "${ROOT}/www/index.html" ]]; then
  WWW_SRC="${ROOT}/www"
fi
if [[ -n "$WWW_SRC" ]]; then
  rsync -a --delete "${WWW_SRC}/" "${INSTALL_ROOT}/www/"
else
  echo "warning: no Consul UI (consul/dist or www/index.html missing — run pi-native-build or cross deploy)" >&2
fi
chmod 755 "${INSTALL_ROOT}/scripts/can-up.sh"
chmod 755 "${INSTALL_ROOT}/scripts/homing-preflight.sh" 2>/dev/null || true
chown -R root:"${RUN_USER}" "${INSTALL_ROOT}/config" "${INSTALL_ROOT}/assets" "${INSTALL_ROOT}/scripts"
chmod -R g+rwX "${INSTALL_ROOT}/config" "${INSTALL_ROOT}/assets" "${INSTALL_ROOT}/scripts"
# Sudo target for gateway restart must not be group-writable by ${RUN_USER}.
if [[ -f "${INSTALL_ROOT}/scripts/pi-restart-marengo-pi.sh" ]]; then
  chown root:root "${INSTALL_ROOT}/scripts/pi-restart-marengo-pi.sh"
  chmod 0755 "${INSTALL_ROOT}/scripts/pi-restart-marengo-pi.sh"
fi

if id "$DEPLOY_USER" &>/dev/null; then
  SUDOERS_PATH="/etc/sudoers.d/marengo-${DEPLOY_USER}"
  SUDOERS_TMP="$(mktemp)"
  cat >"$SUDOERS_TMP" <<EOF
# Marengo bench automation (${DEPLOY_USER}) - generated by scripts/install-pi.sh
${DEPLOY_USER} ALL=(root) NOPASSWD: ${INSTALL_ROOT}/scripts/can-up.sh *
${DEPLOY_USER} ALL=(root) NOPASSWD: ${INSTALL_ROOT}/scripts/pi-restart-marengo-pi.sh
${DEPLOY_USER} ALL=(root) NOPASSWD: ${INSTALL_ROOT}/scripts/pi-restart-marengo-pi.sh *
${DEPLOY_USER} ALL=(root) NOPASSWD: ${INSTALL_ROOT}/scripts/install-pi.sh
${DEPLOY_USER} ALL=(root) NOPASSWD: /home/${DEPLOY_USER}/marengo/scripts/install-pi.sh
EOF
  chmod 440 "$SUDOERS_TMP"
  if visudo -cf "$SUDOERS_TMP" >/dev/null; then
    install -m 440 "$SUDOERS_TMP" "$SUDOERS_PATH"
  else
    echo "warning: generated sudoers failed validation; not installing ${SUDOERS_PATH}" >&2
  fi
  rm -f "$SUDOERS_TMP"
fi

# Gateway (User=${RUN_USER}) may restart marengo-pi via the canonical script only.
if id "$RUN_USER" &>/dev/null; then
  RUN_SUDOERS_PATH="/etc/sudoers.d/marengo-${RUN_USER}-restart"
  RUN_SUDOERS_TMP="$(mktemp)"
  cat >"$RUN_SUDOERS_TMP" <<EOF
# Marengo gateway control-loop restart (${RUN_USER}) - generated by scripts/install-pi.sh
${RUN_USER} ALL=(root) NOPASSWD: ${INSTALL_ROOT}/scripts/pi-restart-marengo-pi.sh restart
EOF
  chmod 440 "$RUN_SUDOERS_TMP"
  if visudo -cf "$RUN_SUDOERS_TMP" >/dev/null; then
    install -m 440 "$RUN_SUDOERS_TMP" "$RUN_SUDOERS_PATH"
  else
    echo "warning: generated restart sudoers failed validation; not installing ${RUN_SUDOERS_PATH}" >&2
  fi
  rm -f "$RUN_SUDOERS_TMP"
fi

mkdir -p /etc/marengo
if [[ ! -f /etc/marengo/env ]]; then
  install -m 640 "${ROOT}/scripts/env.example" /etc/marengo/env
  chown root:"${RUN_USER}" /etc/marengo/env
fi
# Migrate renamed default bench profiles.
if [[ -f /etc/marengo/env ]] && grep -q 'arm_2dof_right' /etc/marengo/env 2>/dev/null; then
  sed -i 's|config/bringup/arm_2dof_right|config/bringup/arm_4dof_right|g' /etc/marengo/env
fi
if [[ -f /etc/marengo/env ]] && grep -q 'arm_3dof_right' /etc/marengo/env 2>/dev/null; then
  sed -i 's|config/bringup/arm_3dof_right|config/bringup/arm_4dof_right|g' /etc/marengo/env
fi

install -m 644 "${ROOT}/scripts/systemd/marengo-can.service" /etc/systemd/system/marengo-can.service
install -m 644 "${ROOT}/scripts/systemd/marengo-pi.service" /etc/systemd/system/marengo-pi.service
install -m 644 "${ROOT}/scripts/systemd/marengo-gateway.service" /etc/systemd/system/marengo-gateway.service
install -m 644 "${ROOT}/scripts/systemd/marengo-log-maintenance.service" /etc/systemd/system/marengo-log-maintenance.service
install -m 644 "${ROOT}/scripts/systemd/marengo-log-maintenance.timer" /etc/systemd/system/marengo-log-maintenance.timer
sed -i "s|WorkingDirectory=.*|WorkingDirectory=${INSTALL_ROOT}|" /etc/systemd/system/marengo-pi.service
sed -i "s|User=.*|User=${RUN_USER}|" /etc/systemd/system/marengo-pi.service
sed -i "s|ExecStart=.*|ExecStart=${INSTALL_ROOT}/bin/marengo-pi|" /etc/systemd/system/marengo-pi.service
sed -i "s|WorkingDirectory=.*|WorkingDirectory=${INSTALL_ROOT}|" /etc/systemd/system/marengo-gateway.service
sed -i "s|User=.*|User=${RUN_USER}|" /etc/systemd/system/marengo-gateway.service
sed -i "s|ExecStart=.*|ExecStart=${INSTALL_ROOT}/bin/marengo-gateway --http-listen [::]:8080 --https-listen [::]:8444 --web-root ${INSTALL_ROOT}/www --wt-listen [::]:8443 --chappe-socket /run/marengo/chappe.sock|" /etc/systemd/system/marengo-gateway.service

# Auto Learn BFF (optional — only when staged with the deploy bundle).
AUTO_LEARN_SRC="${ROOT}/tools/compound-auto-learn"
AUTO_LEARN_DST="${INSTALL_ROOT}/tools/compound-auto-learn"
AUTO_LEARN_NODE_VER="v24.16.0"
AUTO_LEARN_NODE_PREFIX="${INSTALL_ROOT}/tools/node"
env_file_has_nonempty() {
  local key="$1"
  local line val
  [[ -f /etc/marengo/env ]] || return 1
  line="$(grep -E "^${key}=" /etc/marengo/env 2>/dev/null | tail -1 || true)"
  [[ -n "$line" ]] || return 1
  val="${line#*=}"
  val="${val%\"}"
  val="${val#\"}"
  val="${val%\'}"
  val="${val#\'}"
  [[ -n "${val//[[:space:]]/}" ]]
}
if [[ -f "${AUTO_LEARN_SRC}/package.json" ]]; then
  echo "Installing Auto Learn BFF → ${AUTO_LEARN_DST}"
  mkdir -p "${INSTALL_ROOT}/tools" "${INSTALL_ROOT}/var/auto-learn-cwd"
  chown "${RUN_USER}:${RUN_USER}" "${INSTALL_ROOT}/var/auto-learn-cwd"

  NEED_NODE=true
  if [[ -x "${AUTO_LEARN_NODE_PREFIX}/bin/node" ]]; then
    if [[ "$("${AUTO_LEARN_NODE_PREFIX}/bin/node" -v 2>/dev/null || true)" == "${AUTO_LEARN_NODE_VER}" ]]; then
      NEED_NODE=false
    fi
  fi
  if [[ "$NEED_NODE" == true ]]; then
    NODE_TARBALL="node-${AUTO_LEARN_NODE_VER}-linux-arm64.tar.xz"
    NODE_URL="https://nodejs.org/dist/${AUTO_LEARN_NODE_VER}/${NODE_TARBALL}"
    NODE_TMP="$(mktemp -d)"
    echo "Installing Node ${AUTO_LEARN_NODE_VER} linux-arm64 → ${AUTO_LEARN_NODE_PREFIX}"
    if command -v curl >/dev/null 2>&1; then
      curl -fsSL "$NODE_URL" -o "${NODE_TMP}/${NODE_TARBALL}"
    else
      wget -qO "${NODE_TMP}/${NODE_TARBALL}" "$NODE_URL"
    fi
    tar -xJf "${NODE_TMP}/${NODE_TARBALL}" -C "$NODE_TMP"
    mkdir -p "$AUTO_LEARN_NODE_PREFIX"
    rsync -a --delete "${NODE_TMP}/node-${AUTO_LEARN_NODE_VER}-linux-arm64/" "${AUTO_LEARN_NODE_PREFIX}/"
    rm -rf "$NODE_TMP"
  fi

  mkdir -p "$AUTO_LEARN_DST"
  rsync -a --delete \
    --exclude node_modules \
    --exclude dist \
    "${AUTO_LEARN_SRC}/" "${AUTO_LEARN_DST}/"
  chown -R "${RUN_USER}:${RUN_USER}" "$AUTO_LEARN_DST" "$AUTO_LEARN_NODE_PREFIX"

  # Build needs esbuild (devDependency); end state matches npm ci --omit=dev + dist/.
  sudo -u "$RUN_USER" env \
    PATH="${AUTO_LEARN_NODE_PREFIX}/bin:/usr/local/bin:/usr/bin" \
    HOME="$(getent passwd "$RUN_USER" | cut -d: -f6)" \
    bash -c "set -euo pipefail; cd '${AUTO_LEARN_DST}'; npm ci; npm run build; npm prune --omit=dev"

  if [[ -f "${ROOT}/scripts/systemd/marengo-auto-learn.service" ]]; then
    install -m 644 "${ROOT}/scripts/systemd/marengo-auto-learn.service" \
      /etc/systemd/system/marengo-auto-learn.service
  fi
fi

chown -R "${RUN_USER}:${RUN_USER}" "${INSTALL_ROOT}"
chown -R root:"${RUN_USER}" "${INSTALL_ROOT}/config" "${INSTALL_ROOT}/assets" "${INSTALL_ROOT}/scripts" "${INSTALL_ROOT}/var" 2>/dev/null || true
chmod -R g+rwX "${INSTALL_ROOT}/config" "${INSTALL_ROOT}/assets" "${INSTALL_ROOT}/scripts" "${INSTALL_ROOT}/var" 2>/dev/null || true
# Auto Learn cwd + tool tree stay owned by the runtime user.
if [[ -d "${INSTALL_ROOT}/var/auto-learn-cwd" ]]; then
  chown "${RUN_USER}:${RUN_USER}" "${INSTALL_ROOT}/var/auto-learn-cwd"
fi
if [[ -d "${AUTO_LEARN_DST}" ]]; then
  chown -R "${RUN_USER}:${RUN_USER}" "$AUTO_LEARN_DST"
fi
if [[ -d "${AUTO_LEARN_NODE_PREFIX}" ]]; then
  chown -R "${RUN_USER}:${RUN_USER}" "$AUTO_LEARN_NODE_PREFIX"
fi

install_deploy_rev "${ROOT}" "${INSTALL_ROOT}"
chown root:root "${INSTALL_ROOT}/.deploy-rev"
chmod 644 "${INSTALL_ROOT}/.deploy-rev"

systemctl daemon-reload
systemctl enable --now marengo-can.service
if [[ -f "${INSTALL_ROOT}/bin/marengo-gateway" ]]; then
  systemctl enable marengo-gateway.service
  systemctl restart marengo-gateway.service
fi
if [[ -f "${INSTALL_ROOT}/bin/marengo-log-cli" ]]; then
  systemctl enable --now marengo-log-maintenance.timer
fi
if [[ -f "${INSTALL_ROOT}/bin/marengo-pi" ]]; then
  systemctl enable marengo-pi.service
  systemctl restart marengo-pi.service
fi
# Enable Auto Learn when installed; start when secrets exist (wrapper exits 0 if unset).
if [[ -f /etc/systemd/system/marengo-auto-learn.service ]]; then
  chmod 755 "${INSTALL_ROOT}/scripts/run-auto-learn.sh" 2>/dev/null || true
  systemctl enable marengo-auto-learn.service
  if env_file_has_nonempty CURSOR_API_KEY && env_file_has_nonempty AUTO_LEARN_TOKEN; then
    systemctl restart marengo-auto-learn.service
  else
    echo "Auto Learn BFF enabled but idle (set CURSOR_API_KEY and AUTO_LEARN_TOKEN in /etc/marengo/env, then: systemctl restart marengo-auto-learn)"
  fi
fi

echo "Done. CAN (can0/can1) should be UP — verify: ip -br link show type can"
if [[ -x "${INSTALL_ROOT}/bin/motor-repl" ]] && [[ -x "${INSTALL_ROOT}/scripts/homing-preflight.sh" ]]; then
  BENCH_CFG="${INSTALL_ROOT}/config/bringup/arm_4dof_right"
  if [[ -f /etc/marengo/env ]] && grep -q '^MARENGO_CONFIG_DIR=' /etc/marengo/env 2>/dev/null; then
    BENCH_CFG="$(grep '^MARENGO_CONFIG_DIR=' /etc/marengo/env | tail -1 | cut -d= -f2- | tr -d "\"'")"
    if [[ "$BENCH_CFG" != /* ]]; then
      BENCH_CFG="${INSTALL_ROOT}/${BENCH_CFG}"
    fi
  fi
  echo ""
  MARENGO_ROOT="${INSTALL_ROOT}" MARENGO_CONFIG_DIR="${BENCH_CFG}" \
    "${INSTALL_ROOT}/scripts/homing-preflight.sh" || true
fi
echo "Next:"
echo "  1. Edit /etc/marengo/env (MARENGO_ROOT, MARENGO_CONFIG_DIR)"
echo "  2. Consul UI: https://marengo.local:8444 (gateway enabled on boot; accept self-signed cert once)"
echo "  3. Bench motion: run marengo-pi / motor-repl manually (do not enable marengo-pi.service unless you want always-on control)"
echo "  4. Example: MARENGO_CONFIG_DIR=config/bringup/arm_4dof_right ${INSTALL_ROOT}/bin/motor-repl status"
echo "  5. Local dev Consul: VITE_CHAPPE_* in consul/.env.local (see consul/.env.example)"
PI_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
if [[ -n "${PI_IP}" ]] && [[ -f /etc/marengo/env ]]; then
  if ! grep -q '^MARENGO_GATEWAY_TLS_EXTRA_SAN=' /etc/marengo/env 2>/dev/null; then
    echo "MARENGO_GATEWAY_TLS_EXTRA_SAN=${PI_IP}" >> /etc/marengo/env
  fi
fi
